name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: List available Xcode versions
       run: ls /Applications | grep Xcode
    - name: Run a one-line script
       run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version
    - name: Run a multi-line script
       run: |
          xcodebuild test -project gamescatalogue.xcodeproj -scheme gamescatalogue -destination "platform=iOS Simulator,name=iPhone 12,OS=15.0.2"
