name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app
    - name: Run tests
      run: xcodebuild clean test -project "gamescatalogue.xcodeproj" -scheme "gamescatalogue" -destination "platform=iOS Simulator,name=iPhone 12,OS=latest"
    - name: Build App
      run: xcodebuild -project "gamescatalogue.xcodeproj" -scheme "gamescatalogue" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
